add sort string function
js-tasks-ru/js-20200928_mr-marashli pull request #2
Opened 2020-10-05 09:25 UTC by thebluekit

2020-10-05 09:31 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return a new sorted array
+ should return sorted by "desc" array of strings in "en" locale
+ should correctly sort language-specific characters in "ru" locale
+ should correctly sort strings started from uppercase
- should correctly sort strings for mixed "en" and "ru" locales
```

2020-10-05 09:42 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return a new sorted array
+ should return sorted by "desc" array of strings in "en" locale
+ should correctly sort language-specific characters in "ru" locale
+ should correctly sort strings started from uppercase
- should correctly sort strings for mixed "en" and "ru" locales
```
```diff
pick
+ should return new object with one passed field
+ should return new object with a few passed field
+ should return an empty object if passed fields does not found
```

2020-10-05 09:58 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return a new sorted array
+ should return sorted by "desc" array of strings in "en" locale
+ should correctly sort language-specific characters in "ru" locale
+ should correctly sort strings started from uppercase
- should correctly sort strings for mixed "en" and "ru" locales
```
```diff
pick
+ should return new object with one passed field
+ should return new object with a few passed field
+ should return an empty object if passed fields does not found
```
```diff
omit
+ should return a new object without passed field
+ should return a new object without few passed fields
+ should return initial object if passed fields doesn't found
```

2020-10-05 15:55 UTC, thebluekit commented
> Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).
> 
> ```diff
> sortStrings
> + should return sorted by "asc" array of strings
> + should return a new sorted array
> + should return sorted by "desc" array of strings in "en" locale
> + should correctly sort language-specific characters in "ru" locale
> + should correctly sort strings started from uppercase
> - should correctly sort strings for mixed "en" and "ru" locales
> ```

На моей машине все тесты проходит, в чем может быть проблема?

2020-10-06 13:51 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    return [...arr].sort(ascSort).reverse();
необходимо избавиться от `reverse`. Посмотрите пожалуйста разбор домашек на занятии

2020-10-06 13:52 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  if (compareResult === 1) {
эти `if` не нужны, достаточно просто вернуть значение `compareResult`

2020-10-06 13:53 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +  const omitedKeys = objKeys.filter(item => fields.indexOf(item) == -1);
почему в решении `omit` Вы итерируете свойства объекта в `filter`, а в решении `pick` итераци происходит по `fields`?

2020-10-06 13:54 UTC, dosandk requested changes
необходимо внести правки согласно комментариям,
дать ответы на вопросы

2020-10-08 19:50 UTC, thebluekit commented on 02-javascript-data-types/3-omit/index.js
> +  const omitedKeys = objKeys.filter(item => fields.indexOf(item) == -1);
В `omit` `filter` на выходе даст мне отфильтрованный массив, с который я буду производить дальнейшие операции, а в `pick` мне не нужен был отфильтрованный массив, мне нужен был новый объект, сформированный по моему условию.
`Omit` решил исправить как Вы показывали на занятии.
Pick оставил таким какой он у меня сейчас, так как на мой взгляд он совершит меньшее количество итераций, в отличии от Вашего метода, который вы показали на занятии, хотя безусловно он удобнее, так как его легко переделать в `omit`. Но возможно я ошибаюсь.

2020-10-08 19:58 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return a new sorted array
+ should return sorted by "desc" array of strings in "en" locale
+ should correctly sort language-specific characters in "ru" locale
+ should correctly sort strings started from uppercase
+ should correctly sort strings for mixed "en" and "ru" locales
```
```diff
pick
+ should return new object with one passed field
+ should return new object with a few passed field
+ should return an empty object if passed fields does not found
```
```diff
omit
+ should return a new object without passed field
+ should return a new object without few passed fields
+ should return initial object if passed fields doesn't found
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-10-09 19:55 UTC, dosandk approved these changes

2020-10-09 19:55 UTC, merged